algorithm_kwargs:
  batch_size: 4
  eval_freq: 2
  num_epochs: 1
  start_epoch: 0
amp: true
dataset_kwargs:
  batch_size: 4
  crop_size: 512
  dataset: ade20k
  image_size: 512
  normalization: deit
  num_workers: 10
  split: train
inference_kwargs:
  im_size: 512
  window_size: 512
  window_stride: 512
log_dir: seg_shard
net_kwargs:
  backbone: shard
  decoder:
    n_cls: 150
    name: linear
  drop_path_rate: 0.1
  dropout: 0.0
  head_permutation: none
  hidden_dims: (32 * 12, 40 * 12, 48 * 12, 56 * 12, 64 * 12)
  image_size: !!python/tuple
  - 512
  - 512
  mlp_dims: (32 * 48, 40 * 48, 48 * 48, 56 * 48, 64 * 48)
  n_cls: 150
  normalization: deit
  num_classes: 1000
  num_heads: (12, 12, 12, 12, 12)
  num_layers: 12
  patch_size: 16
  pretrained_model: /var/scratch/skalra/pretrained/flexdeit_v3.pt
optimizer_kwargs:
  clip_grad: null
  epochs: 1
  iter_max: 2527
  iter_warmup: 0.0
  lr: 0.001
  min_lr: 1.0e-05
  momentum: 0.9
  opt: sgd
  poly_power: 0.9
  poly_step_size: 1
  sched: polynomial
  weight_decay: 0.0
resume: false
version: normal
world_batch_size: 8
